/* Generated By:JavaCC: Do not edit this line. Eg4TreeConstants.java Version 5.0 */
package com.dobest.irondb.metastore.javacc.JJTreeExamples;

public interface Eg4TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYOTHERID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyOtherID",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=00d6f7d66b32bfdeb94f5749dc2c70d8 (do not edit this line) */
