/* Generated By:JavaCC: Do not edit this line. Eg4Visitor.java Version 5.0 */
package com.dobest.irondb.metastore.javacc.JJTreeExamples;

public interface Eg4Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTMyOtherID node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=9a956ec843ce7ddcd4a15a6be631f3b3 (do not edit this line) */
